### ISSUE TITLE
allow custom ignored-mount-points

### ISSUE THREAD

**Issue by blockloop** [cloudalchemy/ansible-node-exporter#106]
You have some default variables [commented out here](https://github.com/cloudalchemy/ansible-node-exporter/blob/3f852639ecece4b9d1df3b09c1d79fa277d202fe/defaults/main.yml#L14-L16) that I'd like to use. Is there another way to do this?

**Comment by paulfantom** [comment]
You should override `node_exporter_enabled_collectors` in your playbook or any other place that is further in [ansible variable precedence list](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable) than "role defaults"
