### ISSUE TITLE
validate the SSL certificate failed from github

### ISSUE THREAD

**Issue by ruccoon** [cloudalchemy/ansible-node-exporter#108]
Hi,

I got the error message when try to run the ansible playbook.

ansible-node-exporter version: 0.15.0
to be installed node-exporter version: 0.18.1

https://github.com/cloudalchemy/ansible-node-exporter/blob/master/tasks/preflight.yml#L71

TASK [node-exporter : Get checksum list from github] ***********************************************************************************************************************************
fatal: [host]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'url'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Error validating the server's certificate for https://github.com/prometheus/node_exporter/releases/download/v0.18.1/sha256sums.txt: Failed to validate the SSL certificate for github.com:443. Make sure your managed systems have a valid CA certificate installed. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/ansible, /usr/local/etc/openssl. The exception msg was: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)."}

Could you help have a look?

Thanks,

**Comment by paulfantom** [comment]
Does `curl https://github.com` also return problems with certs? What is the python version installed on target host? What operating system is used on target host? Which ansible version is used?

**Comment by bswinnerton** [comment]
I too am having trouble with this step and I believe it may be related, though the step never times out for me, it simply hangs on:

```
TASK [cloudalchemy.node-exporter : Get checksum list from github] ********************************************************************************************

```

I am able to manually curl just fine:

```
$ curl -L https://github.com/prometheus/node_exporter/releases/download/v0.18.1/sha256sums.txt
61a13b13f5a98bafd6e0dec17c6579acbc13f8a1e24a8e9206a8017edb248460  node_exporter-0.18.1.darwin-386.tar.gz
20fadb3108de0a9cc70a1333394e5be90416b4f91025f9fc66f5736335e94398  node_exporter-0.18.1.darwin-amd64.tar.gz
a6c7eb64bb5f27a5567d545a1b93780f3aa72d0627751fd9f054626bb542a4b5  node_exporter-0.18.1.linux-386.tar.gz
b2503fd932f85f4e5baf161268854bf5d22001869b84f00fd2d1f57b51b72424  node_exporter-0.18.1.linux-amd64.tar.gz
d5a28c46e74f45b9f2158f793a6064fd9fe8fd8da6e0d1e548835ceb7beb1982  node_exporter-0.18.1.linux-arm64.tar.gz
1eecbaa2a7e58dc2a5b18e960c48842e5e158c9e2eea4d8a4ba32b98ca2f638a  node_exporter-0.18.1.linux-armv5.tar.gz
6f3cb593c15c12cdfaef20d7e1c61d28ef822af6fc8c85d670cb3f0a1212778a  node_exporter-0.18.1.linux-armv6.tar.gz
5de85067f44b42b22d62b2789cb1a379ff5559649b99795cd1ba0c144b512ad0  node_exporter-0.18.1.linux-armv7.tar.gz
9ef7c932970bc823a63347c3cdd8a34a4ef9d327cd5513600435dfd74d046755  node_exporter-0.18.1.linux-mips.tar.gz
c2721c1b85e3024e61f37fb2dc44a57f6d4eed8cc0576185a1dedea20e36fb31  node_exporter-0.18.1.linux-mips64.tar.gz
ae262af96dd7409aeefe28f8ea6cb1b00377444837057ed67694d8fa1b75b848  node_exporter-0.18.1.linux-mips64le.tar.gz
40860be242f563e3e10972685f1d1654c9b5ca9686b26bde4a422f57a1ebdd18  node_exporter-0.18.1.linux-mipsle.tar.gz
b41f860dbe23b72cf2ae939dd6bb43ea3ddde268f5a964cf6f8d490fed1ed034  node_exporter-0.18.1.linux-ppc64.tar.gz
27996a62327e07041b5dd2f09d6054c7c21244e39358da5d9b44b96daf6a2bc0  node_exporter-0.18.1.linux-ppc64le.tar.gz
0bc212b9db6c2201b2b38d46de2d4cc75b7f4648d7616a87d7616e85f0d6cba4  node_exporter-0.18.1.linux-s390x.tar.gz
c831801b5730750177893a9866416ebb68977a8fd5a7b5305e39ef1162e146a9  node_exporter-0.18.1.netbsd-386.tar.gz
4772c8e2d13935d2bcfa8ad1fd64b8ca5d2cc5d71bbee6dd4ef04306017c6368  node_exporter-0.18.1.netbsd-amd64.tar.gz
```

**Comment by paulfantom** [comment]
@bswinnerton What is the python version installed on target host? What operating system is used on target host? Which ansible version is used?

**Comment by bswinnerton** [comment]
> What is the python version installed on target host?

```
$ python --version
Python 2.7.16
```

> What operating system is used on target host?

```
$ cat /etc/debian_version
10.1
```

> Which ansible version is used?

```
$ ansible --version
ansible 2.8.5
  config file = None
  configured module search path = ['/Users/brooks/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.8.5/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.4 (default, Sep  7 2019, 18:27:02) [Clang 10.0.1 (clang-1001.0.46.4)]
```

**Comment by ruccoon** [comment]
> What is the python version installed on target host?
Python 2.7.16

> What operating system is used on target host?
# cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"

> Which ansible version is used?
ansible 2.4.2.0

**Comment by paulfantom** [comment]
I tried to reproduce it, but it works for me ¯\_(ツ)_/¯.

What I did is the following:
1. installed fresh debian 10.1 and `apt update && apt upgrade -y`
2. installed ansible with pip
3. Ran this role without changing anything (I executed it with `-c local` ansible flag)

Everything seems to work.

**Comment by ruccoon** [comment]
thanks @paulfantom

**Comment by asomir** [comment]
I have the same problem on ubuntu :(

**Comment by kyusupov33** [comment]
The same with [cloudalchemy.node-exporter : Get checksum list from github] Task

Get a python system error
--> 
    __TEXT                 0000000104d03000-0000000104d05000 [    8K] r-x/r-x SM=COW  /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python


ansible --version
WARNING: Executing a script that is loading libcrypto in an unsafe way. This will fail in a future version of macOS. Set the LIBRESSL_REDIRECT_STUB_ABORT=1 in the environment to force this into an error.
ansible 2.8.5
  config file = ...
  configured module search path = [u'/Users/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.16 (default, Oct 17 2019, 17:14:30) [GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.32.4) (-macos10.15-objc-s

**Comment by kyusupov33** [comment]
If you also encountered this problem on Mac OS Catalina, then wrap ansible in docker, like this - https://github.com/walokra/docker-ansible-playbook and run it from docker.

**Comment by paulfantom** [comment]
@kyusupov33 that container image should be updated, as python2 is no longer supported (as of 01.01.2020 - https://www.python.org/doc/sunset-python-2/)
