### ISSUE TITLE
Add Support for over proxy installation

### ISSUE THREAD

**Issue by matanbaruch** [cloudalchemy/ansible-node-exporter#147]
**What happened?**
Cannot fetch binaries over proxy

**How to reproduce it (as minimally and precisely as possible)**:
We would like to export a proxy to the machine and use that proxy
export https_proxy=https://proxy-server:8080; ansible-playbook -i hosts playbook.yml

**Environment**

Linux

* Ansible version information:

ansible 2.8.0

* Ansible playbook execution Logs:

```
fatal: [host01]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'url'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Failed lookup url for https://github.com/prometheus/node_exporter/releases/download/v0.18.1/sha256sums.txt : <urlopen error [Errno 111] Connection refused>"}
```

**Anything else we need to know?**:
Please add 
```
validate_certs: False
```
In here
https://github.com/cloudalchemy/ansible-node-exporter/blob/master/tasks/preflight.yml#L78
https://github.com/cloudalchemy/ansible-node-exporter/blob/master/tasks/install.yml#L23

Same as
https://github.com/cloudalchemy/ansible-node-exporter/blob/master/tasks/preflight.yml#L58

**Comment by mickaeltr** [comment]
Hello,
We're hitting the same problem with a Squid proxy.
Would that be an option to add a flag to disable certificate validation, to workaround this: https://github.com/ansible/ansible/issues/32750 ?
