### ISSUE TITLE
Support for node-exporter-textfile-collector-scripts 

### ISSUE THREAD

**Issue by sgargel** [cloudalchemy/ansible-node-exporter#164]
It would be nice if this role can automate the deployment of those useful scripts:

https://github.com/prometheus-community/node-exporter-textfile-collector-scripts

**Comment by paulfantom** [comment]
WIP PR is in #141

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**
