### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by till** [cloudalchemy/ansible-node-exporter#167]
**What happened?**

```
TASK [ansible-node-exporter : Create node_exporter config directory] ***********
    fatal: [centos8]: UNREACHABLE! => {"changed": false, "msg": "Failed to create temporary directory.In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\", for more error information use -vvv. Failed command was: ( umask 77 && mkdir -p \"` echo OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused \"process_linux.go:90: adding pid 28027 to cgroups caused \\\"failed to write 28027 to cgroup.procs: write /sys/fs/cgroup/cpu,cpuacct/docker/6bffe942ab289f6018c910fcb7b67957333e050d435ffbe3bbfedb72effead8d/cgroup.procs: invalid argument\\\"\": unknown/.ansible/tmp `\"&& mkdir OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused \"process_linux.go:90: adding pid 28027 to cgroups caused \\\"failed to write 28027 to cgroup.procs: write /sys/fs/cgroup/cpu,cpuacct/docker/6bffe942ab289f6018c910fcb7b67957333e050d435ffbe3bbfedb72effead8d/cgroup.procs: invalid argument\\\"\": unknown/.ansible/tmp/ansible-tmp-1595086095.7307746-27669-8276321652003 && echo ansible-tmp-1595086095.7307746-27669-8276321652003=\"` echo OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused \"process_linux.go:90: adding pid 28027 to cgroups caused \\\"failed to write 28027 to cgroup.procs: write /sys/fs/cgroup/cpu,cpuacct/docker/6bffe942ab289f6018c910fcb7b67957333e050d435ffbe3bbfedb72effead8d/cgroup.procs: invalid argument\\\"\": unknown/.ansible/tmp/ansible-tmp-1595086095.7307746-27669-8276321652003 `\" ), exited with result 1", "unreachable": true}
```

**Did you expect to see some different?**

A working test.

**Maybe fix?**

I think I had similar issues with Github Actions. Could be multiple things:

 1. I remember that essentially the Docker in Docker failed because of the filesystem. You can't have overlay on overlay. One of them has to be vfs for example.
 2. Or it's buggy Docker?
 3. Or it's Travis-CI.

Should we try to fix this?

**Comment by paulfantom** [comment]
What is the environment for test execution?

**Comment by till** [comment]
CentOS8

**Comment by paulfantom** [comment]
> I remember that essentially the Docker in Docker failed because of the filesystem

Tests are not aimed to be run with DinD, that's one of the reasons behind using `tox`. How to run tests is described already in readme at https://github.com/cloudalchemy/ansible-node-exporter#local-testing

> Or it's buggy Docker?

Maybe. However, if you start any container and you are able to write to /tmp in it, then it is fine.

> Or it's Travis-CI.

Travis CI works. We schedule VM-per-ansible version, inside VM we launch molecule tests where each target is separate docker container.

> Should we try to fix this?

If running `tox` inside a clean repository doesn't work, then yes. If it works, then I don't see any bug.

**Comment by till** [comment]
https://travis-ci.com/github/cloudalchemy/ansible-node-exporter/jobs/363897218

**Comment by till** [comment]
Not sure what happened there. Any idea how to fix?

**Comment by paulfantom** [comment]
This is some sort of flakiness in molecule itself. I have no solution apart from hitting "restart job"

**Comment by paulfantom** [comment]
Should be fixed by recent migration to molecule v3 and ditching tox. If this is still an issue please reopen.
