### ISSUE TITLE
Role fails to unpack node_exporter binary

### ISSUE THREAD

**Issue by filippo-form3** [cloudalchemy/ansible-node-exporter#177]
**What happened?**
Role fails to unpack node_exporter binary because of file permissions.

Maybe related to this security fix in ansible: https://github.com/ansible/ansible/issues/67794

**Did you expect to see some different?**
I was expecting the installation to succeed as with previous versions of ansible.

**How to reproduce it (as minimally and precisely as possible)**:
Use version of ansible = 2.9.12.

**Environment**

* Role version:

    `0.21.3`

* Ansible version information:

    `2.9.12`
    

* Variables:

```
insert role variables relevant to the issue
```

* Ansible playbook execution Logs:

```
    qemu: TASK [node-exporter : Download node_exporter binary to local folder] ***********
    qemu: changed: [localhost]
==> qemu: [WARNING]: File '/tmp/node_exporter-1.0.1.linux-amd64.tar.gz' created with
==> qemu: default permissions '600'. The previous default was '666'. Specify 'mode' to
==> qemu: avoid this warning.
    qemu:
    qemu: TASK [node-exporter : Unpack node_exporter binary] *****************************
    qemu: fatal: [localhost]: FAILED! => {"changed": false, "msg": "an error occurred while trying to read the file '/tmp/node_exporter-1.0.1.linux-amd64.tar.gz': [Errno 13] Permission denied: '/tmp/node_exporter-1.0.1.linux-amd64.tar.gz'"}

```

**Comment by FilippoProjetto** [comment]
Proposed fix: https://github.com/cloudalchemy/ansible-node-exporter/pull/178
