### ISSUE TITLE
Dash ('-') in collection name seems not supported

### ISSUE THREAD

**Issue by MartinHerren** [cloudalchemy/ansible-node-exporter#199]
The dash ('-') seems not allowed anymore in collection names. It seems it was previously allowed:
```
❯ ansible-galaxy collection install cloudalchemy.node-exporter
Process install dependency map
ERROR! Invalid collection name 'cloudalchemy.node-exporter', name must be in the format <namespace>.<collection>. Please make sure namespace and collection name contains characters from [a-zA-Z0-9_] only.
```

Tested with ansible version 2.9.16, both setting python_interpreter to python2 and python3

**Comment by paulfantom** [comment]
Fixed with https://github.com/cloudalchemy/ansible-node-exporter/commit/0d9f5037776de01450a4cfb1dcf58e36a393cfae
