### ISSUE TITLE
disruptive role name change on galaxy

### ISSUE THREAD

**Issue by gizero** [cloudalchemy/ansible-node-exporter#205]
Commit https://github.com/cloudalchemy/ansible-node-exporter/commit/0d9f5037776de01450a4cfb1dcf58e36a393cfae changed the role name on Ansible Galaxy from `node-exporter` to `node_exporter`. I understand that role names with dashes are deprecated, but this change is disruptive and I don't even see it mentioned in the commit message! This is not only breaking projects using latest version: even those pinned to a release tag are now failing to download the role. Documentation is now out of sync as well. What's the maintainer's opinion on this?

**Comment by paulfantom** [comment]
We are very sorry for the breaking change. However, we cannot be responsible for 3rd party site limitations and its lack of persistence and redirects. We can only document this now, hence https://github.com/cloudalchemy/ansible-node-exporter/pull/206.

**Comment by paulfantom** [comment]
Side note: the cloudalchemy project is purely community-based, there is no company behind it and we do all the maintenance work in our free time. If you would like to contribute to the project and possibly prevent such issues in the future - feel free to pick up issues we have, help us triage bugs, and in time you too can become a maintainer :)

**Comment by SuperQ** [comment]
All fixed

**Comment by SuperQ** [comment]
Sorry about that. I didn't realize the ansible galaxy system would just completely break old versions. I didn't even tag the change with a new release.

**Comment by gizero** [comment]
@paulfantom Didn't mean to blame anyone for this. Just came across this as a very-breaking change and took some time to figure out what was going on from commit history. Making linters happy and sticking with best practices is something I have to deal with daily and it definitely often lead to compromises to find.

@superQ Yep! Figuring out such a big change was imported even without a release tag was my first source of disappointment. My report was mainly meant to figure out whether this was intentional or not.

All that said, I haven't looked into it much, but maybe a good idea could be to publish the role again with the old name as well (don't even know if Galaxy allows or not). This could make all references to the old name/versions still work.
