### ISSUE TITLE
allow options  --diff --check to work

### ISSUE THREAD

**Issue by dorchain** [cloudalchemy/ansible-node-exporter#222]
ansible-playbook main.yml --diff --check failes when using "latest" as the version

* Role version:

dc266fd1ea0a7656ceefdf1c2a954c007a281693

* Ansible version information:

ansible 2.7.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
From Debian stable

Patch:

diff --git a/tasks/preflight.yml b/tasks/preflight.yml
index da1ef47..b1f2f90 100644
--- a/tasks/preflight.yml
+++ b/tasks/preflight.yml
@@ -83,6 +83,7 @@
         password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
       no_log: "{{ not lookup('env', 'MOLECULE_DEBUG') | bool }}"
       register: _latest_release
+      check_mode: no
       until: _latest_release.status == 200
       retries: 5

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**
