### ISSUE TITLE
Unpack node_exporter binary step fails on cluster

### ISSUE THREAD

**Issue by sjpb** [cloudalchemy/ansible-node-exporter#242]
**What happened?**
Task "Unpack node_exporter binary" fails when running on a vagrant cluster in CI.  I've had this happen a number of times, rerunning usually fixes it.

Interestingly I've never had the same thing happen on a real cluster.

**Did you expect to see some different?**
Yes

**How to reproduce it (as minimally and precisely as possible)**:
Difficult!

**Environment**

* Role version:

galaxy latest

* Ansible version information:

4.5.0

* Variables:

* Ansible playbook execution Logs:

Looking at the [source](https://github.com/cloudalchemy/ansible-node-exporter/blob/18ff8f8833b1e357ce91bee6832c3a3d16e709f2/tasks/install.yml#L35) this delegates to localhost, but there's no `run_once: true`, so to me it looks plausible this is a race condition when running on multiple hosts?

Sorry I know this is a slightly rubbish bug report but it's the best I can do at present!

**Comment by zeroZshadow** [comment]
I've been noticing this as well. It's also running all "localhost" tasks once for every host i'm attempting to deploy too, which is quite a lot.

**Comment by iroan** [comment]
I have the same problem and can fix it by manually decompressing the file.

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**
