### ISSUE TITLE
Allow to install node exporter easily without internet

### ISSUE THREAD

**Issue by XDavidT** [cloudalchemy/ansible-node-exporter#251]
**What is missing?**
What if my servers don't have access to the internet? any option to provide them with the file locally?

**Why do we need it?**
Not all servers connected to internet
**Environment**
Ubuntu servers

**Comment by maxtruxa** [comment]
`node_exporter_binary_local_dir` does this already, doesn't it?

**Comment by XDavidT** [comment]
> `node_exporter_binary_local_dir` does this already, doesn't it?

I'm not sure, even after use it, the task failing [here](https://github.com/cloudalchemy/ansible-node-exporter/blob/18ff8f8833b1e357ce91bee6832c3a3d16e709f2/tasks/install.yml#L21)

**Comment by maxtruxa** [comment]
That task [does not run if you set `node_exporter_binary_local_dir`](https://github.com/cloudalchemy/ansible-node-exporter/blob/18ff8f8833b1e357ce91bee6832c3a3d16e709f2/tasks/install.yml#L53). Are you sure you set the var correctly? Try inserting a debug task right before the block to see if the var is set:

```yaml
- debug:
    var: node_exporter_binary_local_dir
```

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**
