### ISSUE TITLE
Create password hash on local machine

### ISSUE THREAD

**Issue by sfischme** [cloudalchemy/ansible-node-exporter#256]
**What is missing?**

Instead of executing bcrypt on the remote machine, execute it on the local machine and transmit the password as a variable.

**Why do we need it?**

Not all remote machines have python installed. Even less have bcrypt. Some have old versions of python.

**Environment**
Various flavours of Linux.

* Role version:

    2.0.0

* Ansible version information:

    2.12.1

**Anything else we need to know?**:

As alternative, let me run bcrypt on the password locally and put the hashed output into the playbook with node_exporter_basic_auth_user not bcrypting the password again.

**Comment by sdarwin** [comment]
> Not all remote machines have python installed. 

wait. ...

Are you proposing to run Ansible without python?

In terms of ansible, this is almost like says "Not all remote machines have ssh installed.".  Which means, you have to fix that, and cannot proceed otherwise.

**Comment by sfischme** [comment]
Even with python, we would also need bcrypt (and pip) just to generate the hash for the password. It would be easier to not have to create the hash on the target machine.

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**
