### ISSUE TITLE
Support for other RHEL-like packages

### ISSUE THREAD

**Issue by sjpb** [cloudalchemy/ansible-node-exporter#260]
**What is missing?**
Support for RHEL clones

**Why do we need it?**
CentOS 8 is EoL, lots of people will be using clones such as Rocky/Alma/Oracle.

**Environment**

* Role version:

    `Insert release version/galaxy tag or Git SHA here`

* Ansible version information:

    `ansible --version`
    

**Anything else we need to know?**:

Currently there's two PRS:
- https://github.com/cloudalchemy/ansible-node-exporter/pull/248
- https://github.com/cloudalchemy/ansible-node-exporter/pull/247

I wonder if the proposed changes would be better fixed by using `ansible_os_family` instead of `ansible_distribution`:

```yaml
 when:
    - (ansible_os_family | lower == "redhat")
```
at https://github.com/cloudalchemy/ansible-node-exporter/blob/master/tasks/selinux.yml#L12

With ansible 2.11 at least, Rocky 8.5 has:
```shell
"{{ ansible_distribution }} {{ ansible_distribution_major_version }} {{ ansible_os_family }}"
Rocky 8 RedHat
```

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**
