### ISSUE TITLE
Create a new release with changes in master branch

### ISSUE THREAD

**Issue by chrodriguez** [cloudalchemy/ansible-node-exporter#270]
New versions of node_exporter uses stdout instead of stderr. These fix is applied in master branch, but release 2.0.0 does not have this fix applied. Can you please create a new release of this role?

Thanks in advance

**Comment by antonr-p2p** [comment]
Hello! Faced the same issue! Please release new version

**Comment by antonr-p2p** [comment]
You can find fixed version in https://github.com/prometheus-community/ansible/tree/main/roles/node_exporter

**Comment by chrodriguez** [comment]
> You can find fixed version in https://github.com/prometheus-community/ansible/tree/main/roles/node_exporter

But using a role from git main branch will break old playbooks, so pinning to a release is a best practice

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**
