### ISSUE TITLE
PreventHome works only if mount is directly under /home

### ISSUE THREAD

**Issue by bmillemathias** [cloudalchemy/ansible-node-exporter#271]
**What happened?**
node-exporter is unable to do a `statfs` if a filesystem is mounted under a subdirectory of `/home/`
error reported
```
"msg="Error on statfs() system call" err="permission **denied"**
```

**How to reproduce it (as minimally and precisely as possible)**:
mount a filesystem under /home/<user>/foobar
launch node-exporter
get the aformentioned error 

**Environment**
linux, ubuntu 18.04

* Role version:
 latest published on galaxy

**Anything else we need to know?**:
The bug is located at this place https://github.com/cloudalchemy/ansible-node-exporter/blob/master/templates/node_exporter.service.j2#L37 
the test should be replaced with `{% for m in ansible_mounts if m.mount.startswith('/home') %}` at least it worked for me.

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**
