### ISSUE TITLE
how can we install node exporter on cents 6.x hosts

### ISSUE THREAD

**Issue by TroubleshooteRJ** [cloudalchemy/ansible-node-exporter#49]
hello, I want to deploy node_exporter on our cantos 6.x nodes but there is no systemd there so how can I deploy it there.

**Comment by paulfantom** [comment]
You cannot. Role needs systemd and CentOS 6 doesn't ship with it. Sorry.

**Comment by TroubleshooteRJ** [comment]
Thanks for your prompt reply. so is there any way we can bring CentOS 6 hosts under prometheus monitoring ..

**Comment by paulfantom** [comment]
It would be pretty easy, you can fork this role and change template for service file from systemd to one compatible with CentOS 6. The rest should work without problems.
