### ISSUE TITLE
Rate limit errors due to checksum fetching

### ISSUE THREAD

**Issue by mineo** [cloudalchemy/ansible-node-exporter#50]
With a large number of hosts, the task "Get checksum for amd64 architecture" usually fails for at least some of them with the following error:

```
fatal: [HOST1]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'url'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Received HTTP error for https://github.com/prometheus/node_exporter/releases/download/v0.16.0/sha256sums.txt : HTTP Error 429: Too Many Requests"}
fatal: [HOST2]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'url'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Received HTTP error for https://github.com/prometheus/node_exporter/releases/download/v0.16.0/sha256sums.txt : HTTP Error 429: Too Many Requests"}
fatal: [HOST3]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'url'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Received HTTP error for https://github.com/prometheus/node_exporter/releases/download/v0.16.0/sha256sums.txt : HTTP Error 429: Too Many Requests"}
fatal: [HOST4]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'url'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Received HTTP error for https://github.com/prometheus/node_exporter/releases/download/v0.16.0/sha256sums.txt : HTTP Error 429: Too Many Requests"}
```

This appears to be because the checksum is fetched for each node (which makes sense, they don't all share the architecture), but is fetched by the controller node, so for 40 amd64 nodes, the controller will fetch the amd64 checksums 40 times.

For now I have locally set `run_once: true in `~/.ansible/...`, but I think this needs a proper solution.

**Comment by paulfantom** [comment]
Possible fix is to create a list of all CPU arch used in deployment and use `run_once` for checksum and download tasks. This would also speed up deployment.

**Comment by paulfantom** [comment]
@mineo could you test if solution from #51 works for you?

**Comment by mineo** [comment]
@paulfantom #51 appears to fix this, thank you! I've only verified it on amd64 nodes, since I don't have access to any other architecture supported by node_exporter (only ppc64le, for which there are no pre-built binaries).

**Comment by paulfantom** [comment]
@mineo Thanks!
