### ISSUE TITLE
Support for darwin (macOS)

### ISSUE THREAD

**Issue by mdavidsen** [cloudalchemy/ansible-node-exporter#52]
Would it be possible to add support for darwin/macOS?

I just switched to using this role for our Linux based hosts; but we have a quite substantial amount of nodes that are running darwin as well.

**Comment by SuperQ** [comment]
Seems like a good idea to me, we can use the `ansible_system` variable for this.

**Comment by paulfantom** [comment]
From my understanding darwin doesn't have systemd which is a hard requirement on this role.

Closing as this is not possible to accomplish with current role design.
