### ISSUE TITLE
Python crashes when running role

### ISSUE THREAD

**Issue by bswinnerton** [cloudalchemy/ansible-node-exporter#54]
I'm not sure if this is related to this particular role, or perhaps Python, but I thought it would be a good idea to document the bug in the event anyone else runs into this, and perhaps the maintainers of this repository have recommendations on how to debug this.

I installed this role by doing the following:

##

`requirements.yml`

```
ansible-galaxy install -r requirements.yml
```

##

`site.yml`

```yaml
- name: Install node_exporter on all bare-metal hosts
  hosts: bare-metal
  roles:
    - cloudalchemy.node-exporter
```

##

And then attempted to do a dry run with:

`ansible-playbook -i ansible/hosts.yml --ask-become-pass --check ansible/site.yml`

The output looks like this:

```
PLAY [Install node_exporter on all bare-metal hosts] ******************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************************************
ok: [nuc7i5b.brooks.network]
ok: [nuc7i5a.brooks.network]
ok: [pi.brooks.network]

TASK [cloudalchemy.node-exporter : Gather variables for each operating system] ****************************************************************************************
fatal: [nuc7i5a.brooks.network]: FAILED! => {"msg": "No file was found when using with_first_found. Use the 'skip: true' option to allow this task to be skipped if no files are found"}
fatal: [nuc7i5b.brooks.network]: FAILED! => {"msg": "No file was found when using with_first_found. Use the 'skip: true' option to allow this task to be skipped if no files are found"}
ok: [pi.brooks.network] => (item=/Users/brooks/.ansible/roles/cloudalchemy.node-exporter/vars/debian.yml)

TASK [cloudalchemy.node-exporter : Naive assertion of proper listen address] ******************************************************************************************
ok: [pi.brooks.network] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [cloudalchemy.node-exporter : Fail on unsupported init systems] **************************************************************************************************
skipping: [pi.brooks.network]

TASK [cloudalchemy.node-exporter : Check collectors] ******************************************************************************************************************

TASK [cloudalchemy.node-exporter : Get checksum list from github] *****************************************************************************************************
objc[93522]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[93522]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork()
child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

And I get this from OSX:

<img width="1112" alt="screen shot 2018-09-17 at 4 00 02 pm" src="https://user-images.githubusercontent.com/934497/45647472-f1884a80-ba93-11e8-93eb-712630c51bdf.png">

I'm running this from MacOS 10.13.6, with Python version `2.7.15` installed from brew.

**Comment by bswinnerton** [comment]
I was able to resolve this by exporting the `OBJC_DISABLE_INITIALIZE_FORK_SAFETY` variable to `YES`.

Via https://github.com/ansible/ansible/issues/31869#issuecomment-337769174.

**Comment by paulfantom** [comment]
Great to see that you solved it! Out of curiosity, may I ask what are you using this role for?

**Comment by lekkerduidelijk** [comment]
I'm seeing similar results on Ubuntu 16 LTS:

```
[..]
TASK [node-exporter : Gather variables for each operating system] ****************************************************************************************
ok: [x.x.x.x] => (item=/Users/[..]/vendor/roles/node-exporter/vars/debian.yml)

TASK [node-exporter : Naive assertion of proper listen address] ******************************************************************************************
ok: [x.x.x.x] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [node-exporter : Fail on unsupported init systems] **************************************************************************************************
skipping: [x.x.x.x]

TASK [node-exporter : Check collectors] ******************************************************************************************************************

TASK [node-exporter : Get checksum list from github] *****************************************************************************************************
objc[69118]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[69118]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

**Comment by paulfantom** [comment]
@lekkerduidelijk this looks like some ansible or python related issue. There is a similar issue in ansible: https://github.com/ansible/ansible/issues/32499

**Comment by lekkerduidelijk** [comment]
@paulfantom Yeah, also setting the env variable feels a bit 'hacky' to me.

One thing I discovered later on, is that the `ansible-node-exporter` playbook runs commands on localhost. Like unzip, untar etc. I'm accustomed to those commands being run on the remote host, so I needed to install some stuff locally first. Like `brew install gnu-tar`.

**Comment by paulfantom** [comment]
Yes, we run those commands to speed up deployment with large number of target hosts and all requirements are specified in readme :)

**Comment by lekkerduidelijk** [comment]
Ok, makes sense. 👍 

When running the playbook with the ENV in place I got:
> Make sure the required command to extract the file is installed. Command "/usr/bin/tar" detected as tar type bsd. GNU tar required. Command "/usr/bin/unzip" could not handle archive.

The binaries for `/usr/bin/tar` and `/usr/bin/unzip` both existed. This is on MacOS Mojave 10.14. 
Adding `gnu-tar` fixed it for me.

Also, I forgot to mention: thanks for your great work on the Ansible playbooks for the Prometheus stack. Huge time savers! 😎
