### ISSUE TITLE
Nice'ness fails node_exporter

### ISSUE THREAD

**Issue by till** [cloudalchemy/ansible-node-exporter#59]
Hello!

Been trying to use this role to install the node exporter on a few servers (VMs).

Ultimately, the Ansible run completes, but the node exporter is not started.

When inspecting `systemctl status` I see the job has reached its start limit, the Journal has this:

```
Oct 25 11:11:03 prometheus.test systemd[14341]: Failed at step NICE spawning /usr/local/bin/node_exporter: Permission denied
Oct 25 11:11:03 prometheus.test systemd[1]: node_exporter.service: main process exited, code=exited, status=201/NICE
Oct 25 11:11:03 prometheus.test systemd[1]: Unit node_exporter.service entered failed state.
Oct 25 11:11:03 prometheus.test systemd[1]: node_exporter.service failed.
Oct 25 11:11:03 prometheus.test systemd[1]: node_exporter.service holdoff time over, scheduling restart.
Oct 25 11:11:03 prometheus.test systemd[1]: Started Prometheus Node Exporter.
Oct 25 11:11:03 prometheus.test systemd[1]: Starting Prometheus Node Exporter...
...
```

I tried starting the node exporter as root, which works, it just fails at nice'ing the process via Systemd when using the user `node-exp` (which is also setup by this role).

I have tried to google how to check which permissions are needed by a user, but I am also stuck checking Systemd internals to see what is happening.

I think I am not doing something very custom here — running this role, a few configuration settings:

```
  vars:
    node_exporter_web_listen_address: "0.0.0.0:9100"
    node_exporter_textfile_dir: "/var/lib/node_exporter"
    node_exporter_disabled_collectors:
      - diskstats
      - mdadm
      - nfs
      - nfsd
      - wifi
      - xfs
      - zfs
```

I noticed the `node_exporter.service` installed by this role is the only one nice'ing the service. All other examples/tutorials etc. don't show that. I suspect there is good reason to do this, thus raising the issue here.

**Comment by paulfantom** [comment]
We should remove setting niceness in service file.
