### ISSUE TITLE
Optimizations

### ISSUE THREAD

**Issue by till** [cloudalchemy/ansible-node-exporter#67]
(Sorry, for lack of better headline/title...)

I had a question about this role, specifically about:
https://github.com/cloudalchemy/ansible-node-exporter/blob/master/tasks/install.yml#L24-L35

Is there a specific reason this is delegated to localhost? It seems downloading and unpacking on the target node would be much better in most cases? 

Then, this part:
https://github.com/cloudalchemy/ansible-node-exporter/blob/master/tasks/install.yml#L52-L60

Seems to happen almost every time. Can we add a "creates" and an initial version check? Any thoughts? I am asking because this setup seems to consume a substantial amount of time on my ansible runs and I am trying to avoid building special purpose playbooks right now and would prefer to be able to re-run this continuously/whenever with the same predicable outcome.

**Comment by paulfantom** [comment]
This is a workaround for nodes which doesn't have direct access to github, for example in corporate firewalled networks.

**Comment by till** [comment]
@paulfantom thoughts on the creates? Or is this still necessary for your use-case?

**Comment by paulfantom** [comment]
Version check would be a nice to have addition to this role.
