### ISSUE TITLE
Node_exporter is not running with fresh install on Debian 9

### ISSUE THREAD

**Issue by MCyprien** [cloudalchemy/ansible-node-exporter#71]
I used this role to install and run node_exporter on a fresh new VM, everything is installed but the service does not run by default.

# Setup
ansible 2.7.7
cloudalchemy.node-exporter 0.12.0

Operating System Debian 9

# What it does

It install the node-exporter, the service and all of what is needed for it to run BUT does not start the service.

# What it should do

Install everything and start the service.

# Step to reproduce

Build a fresh instance of Debian 9 and run the playbook with default values on it.

**Comment by angristan** [comment]
I assume this issue can be closed since #72 was merged.
