### ISSUE TITLE
IPv4 assumption in SELinux tasks

### ISSUE THREAD

**Issue by mnaser** [cloudalchemy/ansible-node-exporter#75]
The following piece of code is actually broken when using IPv6 because it assumes an IPv4 address:

https://github.com/cloudalchemy/ansible-node-exporter/blob/c8e279695f74e592f9829a691c51bc43733e3cc8/tasks/configure.yml#L21-L29

**Comment by paulfantom** [comment]
I would appreciate it very much if you could you test if changing:
```
ports: "{{ node_exporter_web_listen_address.split(':')[1] }}"
```
into
```
ports: "{{ node_exporter_web_listen_address.split(':')[-1] }}"
```
makes it IPv6 compatible. Could you do it?
