### ISSUE TITLE
Disable collectors

### ISSUE THREAD

**Issue by till** [cloudalchemy/ansible-node-exporter#80]
```
TASK [cloudalchemy.node-exporter : Assert collectors are not both disabled and enabled at the same time] ***
failed: [host] (item=diskstats) => {
    "assertion": "item in node_exporter_enabled_collectors",
    "changed": false,
    "evaluated_to": false,
    "item": "diskstats",
    "msg": "Assertion failed"
}
failed: [host] (item=mdadm) => {
    "assertion": "item in node_exporter_enabled_collectors",
    "changed": false,
    "evaluated_to": false,
    "item": "mdadm",
    "msg": "Assertion failed"
}
```

I recently updated the role locally and it started failing with the above message. I think this check was introduced in #22. How do you disable what is enabled by this role (by default)? So far, I was using the role and disabled the collectors that I didn't need and it worked — node-exporter didn't use the collector for e.g. mdam or diskstats.

With #22, my deploy stalls as the collector is enabled by default, but I can't disable it anymore.

Do I need to now explicitly set all enabled **and** disabled?

**Comment by paulfantom** [comment]
> Do I need to now explicitly set all enabled and disabled?

Yes, you need to overwrite both `node_exporter_enabled_collectors` and `node_exporter_disabled_collectors`

**Comment by till** [comment]
@paulfantom that seems to be new then? I'll go ahead and do that now.

**Comment by till** [comment]
I believe I set them both "correctly" now, but maybe I mis-understood.

Some sample configurations:

```
# play.yml
- hosts: all
  roles:
     - { role: cloudalchemy.node-exporter }
```

```
# group_vars/all.yml
node_exporter_enabled_collectors:
  - arp
  - bcache
  - bonding
  - boottime
  - conntrack
  - cpu
  - cpufreq
  - edac
  - entropy
  - exec
  - filefd
  - filesystem
  - hwmon
  - ipvs
  - loadavg
  - meminfo
  - netclass
  - netdev
  - netstat
  - sockstat
  - stat
  - textfile
  - time
  - timex
  - uname
  - vmstat
node_exporter_disabled_collectors:
  - diskstats
  - infiniband
  - mdadm
  - nfs
  - nfsd
  - wifi
  - xfs
  - zfs
```

Error "persists", e.g. it's complaining about e.g, "wifi" which is now only in `node_exporter_disabled_collectors`. Is there anything I am missing?

Here is a log, it repeats for all my hosts in `all` — same collectors:

```
TASK [cloudalchemy.node-exporter : Assert collectors are not both disabled and enabled at the same time] ***
failed: [host] (item=diskstats) => {
    "assertion": "item in node_exporter_enabled_collectors",
    "changed": false,
    "evaluated_to": false,
    "item": "diskstats",
    "msg": "Assertion failed"
}
failed: [host] (item=infiniband) => {
    "assertion": "item in node_exporter_enabled_collectors",
    "changed": false,
    "evaluated_to": false,
    "item": "infiniband",
    "msg": "Assertion failed"
}
failed: [host] (item=mdadm) => {
    "assertion": "item in node_exporter_enabled_collectors",
    "changed": false,
    "evaluated_to": false,
    "item": "mdadm",
    "msg": "Assertion failed"
}
failed: [host] (item=nfs) => {
    "assertion": "item in node_exporter_enabled_collectors",
    "changed": false,
    "evaluated_to": false,
    "item": "nfs",
    "msg": "Assertion failed"
}
failed: [host] (item=nfsd) => {
    "assertion": "item in node_exporter_enabled_collectors",
    "changed": false,
    "evaluated_to": false,
    "item": "nfsd",
    "msg": "Assertion failed"
}
failed: [host] (item=wifi) => {
    "assertion": "item in node_exporter_enabled_collectors",
    "changed": false,
    "evaluated_to": false,
    "item": "wifi",
    "msg": "Assertion failed"
}
failed: [host] (item=xfs) => {
    "assertion": "item in node_exporter_enabled_collectors",
    "changed": false,
    "evaluated_to": false,
    "item": "xfs",
    "msg": "Assertion failed"
}
failed: [host] (item=zfs) => {
    "assertion": "item in node_exporter_enabled_collectors",
    "changed": false,
    "evaluated_to": false,
    "item": "zfs",
    "msg": "Assertion failed"
}
```

Again, it seemed to have worked before. Isn't this is a hefty BC break?

**Comment by till** [comment]
Also related: https://github.com/cloudalchemy/ansible-node-exporter/pull/24/files

**Comment by till** [comment]
Am I reading something wrong? Both PRs seem to be in this for over a year, but I am also sure when I initially started using this, it had a full list of enabled collectors in `defaults/main.yml`.

**Comment by paulfantom** [comment]
Seems like I introduced a bug with https://github.com/cloudalchemy/ansible-node-exporter/pull/79. Will fix it soon.

Full list of enabled collectors was removed as we decided to use collectors enabled in node_exporter by default and extend it by using `systemd` (on which cloudalchemy roles depend) and configure `filesystem` collector.

**Comment by paulfantom** [comment]
Should be fixed now. :+1: 

I see you are based in Berlin, come to next prometheus meetup (April 17th) :smile:

**Comment by till** [comment]
@paulfantom What do I google to find it? I saw one on meetup, but there are no new events listed.

**Comment by paulfantom** [comment]
Soon there should be an announcement in https://www.meetup.com/Berlin-Prometheus-Meetup/
