### ISSUE TITLE
Wrong dependencies on RHEL 8

### ISSUE THREAD

**Issue by h3po** [cloudalchemy/ansible-node-exporter#95]
On current RHEL, the dependency packages are python3-libselinux and python3-policycoreutils.

**Comment by paulfantom** [comment]
[RHEL8 is not currently supported](https://github.com/cloudalchemy/ansible-node-exporter/blob/36e1ff4ae924d26344ba60e04805eec1fe04eba4/meta/main.yml#L17-L19) as there is no CentOS8 released and I don't have a docker image to run tests on.

Once an image with CentOS8 shows up I will update supported platform matrix.

**Comment by paulfantom** [comment]
This was fixed in https://github.com/cloudalchemy/ansible-node-exporter/pull/101
